# Use `make regen` to synchronize shared keys with argfile.conf.

## shared (synced from argfile.conf)

BASE_IMAGE=registry.access.redhat.com/ubi10/ubi-minimal:10.2
BASE_IMAGE_REVISION=1

## labels

VARIANT=base
NAME=agentic-base
SUMMARY=Red Hat AI Agentic Base Image
